### PR TITLE
[13.0][ADD] stock_picking_manual_package: New module to select or create the package to do "put in pack"

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

Moved from this repo: https://github.com/OCA/stock-logistics-warehouse/pull/1430

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Let's use the bot to rebase and merging as approved in the other repo:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@sergio-teruel it seems you have to rebase and change manifest URL

**Comment by sergio-teruel** [comment]
@pedrobaeza rebase done and fixed pre-commit!!!

**Pull request merged**
