### PR TITLE
7.0-fix pep8 in ported modules + remove broken method from stock tracking extend

### PR DESCRIPTION
**Pull request by florian-dacosta**

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1: Well done

**Comment by pedrobaeza** [comment]
:+1:

**Comment by max3903** [comment]
```
2015-06-02 08:07:16,441 26271 INFO 2947917-7-69b8a4-all openerp.modules.loading: module stock_product_category_tracked: loading product_category_view.xml
2015-06-02 08:07:16,443 26271 WARNING 2947917-7-69b8a4-all openerp.addons.base.ir.ir_ui_view: Setting the `type` field is deprecated in the `ir.ui.view` model.
```

**Comment by florian-dacosta** [comment]
it is green now!

**Comment by Doscaal** [comment]
:+1:

**Pull request merged**
