### PR TITLE
[16.0][ADD] stock_quant_package_multi_reference

### PR DESCRIPTION
**Pull request by angelinaanaki**

### CODE REVIEW

**Review by ivs-cetmix — APPROVED** [review]
Functional OK

**Review by GabbasovDinar — APPROVED** [review]
Not tested, code seems ok for me

**Comment by ivs-cetmix** [comment]
hey @OCA/logistics-maintainers any chance to get this merged?

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Pull request merged**
