### PR TITLE
[IMP] stock_quant_package_multi_reference: Performance

### PR DESCRIPTION
**Pull request by GabbasovDinar**
Improve search speed when searching packages by name.

Task 4049

### CODE REVIEW

**Review by Bearnard21 — APPROVED** [review]
LGTM
Performance increased 0.13 ms -> 0.05 ms

**Review by ivs-cetmix — APPROVED** [review]
Code review LGTM

**Comment by ivs-cetmix** [comment]
Hey @OCA/logistics-maintainers would appreciate someone having a look at this. It's an update for existing module which brings significant performance improvements 🚀

**Review by rousseldenis — COMMENTED** [review]
That's a great improvement! Thanks

**Review by rousseldenis — APPROVED** [review]

**Review by geomer198 — APPROVED** [review]

**Review by hoangtrann — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
